Feature/dialogflow integration
greatnonprofits-nfp/goflow pull request #18
Opened 2022-05-30 15:29 UTC by musamusa

https://communityconnectlabs.atlassian.net/browse/CD-3

2022-06-02 17:48 UTC, teehamaral requested changes

2022-06-02 17:48 UTC, teehamaral commented on flows/actions/testdata/call_dialogflow.json
> +[]
Can we add some test data? Seems to be basically the JSON definitions from a flow that has the Call DialogFlow flow step in there.

2022-06-02 17:48 UTC, teehamaral commented on services/classification/dialogflowcl/client.go
> +	sessionID := fmt.Sprintf("%s%s", projectID, languageCode)
This session ID is part of the session path, right? So seems that should be unique. I would suggest using here the contact UUID making sure that's unique.

2022-06-02 17:48 UTC, teehamaral commented on flows/actions/call_dialogflow.go
> +		return errors.Errorf("id is required on Giftcard DB")
Would be `id is required on DialogFlow DB`

2022-06-07 05:25 UTC, ihor-palii approved these changes

2022-06-07 18:05 UTC, merged